### ISSUE TITLE
support press down and press up events separately

### ISSUE THREAD

**Issue by es183923** [FelixKratz/SketchyBar#101]
Right now, scripts are triggered when the click is released, and there is no way to get an event when the click is pressed down. It'd be nice to have an option both of them.

in v3, maybe `mouse.clicked` is sent on mouse down, and `mouse.released` is sent on mouse up.

**Comment by FelixKratz** [comment]
Since mouse clicked and released are usually triggered shortly after each other and the scripts running async, this could generate race conditions and sketchy bugs, this is why it is not possible currently.

However, if you want to have an "animation" where the background is highlighted on click and dimmed on release, I would go for a `sleep` in the mouse.clicked script and change the background before and after the sleep, giving the illusion of an animation. This will not block sketchybar, since scripts run async.
