### ISSUE TITLE
clear/no background is click-through

### ISSUE THREAD

**Issue by es183923** [FelixKratz/SketchyBar#106]
item:
```sh
sketchybar -m --add item test left --set test label="a         a"
```
When clicking on the empty space between the two a's, I can click on the things under the bar.

bar config:
```sh
sketchybar -m \
    --bar \
        height=25 \
        position=top \
        blur_radius=1000 \
        corner_radius=10 \
        topmost=on \
        color=0x01000000 \
        font_smoothing=on
```

Is this supposed to be the correct behavior? If so, adding an option `clickthrough` would be nice.

**Comment by FelixKratz** [comment]
Yes this is indeed the wanted behavior. If the bar/an item is transparent we do not wish to steal click events for windows below the bar. Imagine a fully transparent bar with some item brackets -- it would feel off if the space between the brackets was not click-trough. The same is true for individual items.

An element is only clickable if it is visually topmost on the display, otherwise it does not receive click events.

**Comment by es183923** [comment]
Could a `clickthrough` option be added?

**Comment by FelixKratz** [comment]
No, but not because I do not want to, but for a technical reason:
The macOS window server does not send a carbon click event to an application if it does not draw anything. I *could* theoretically solve this by utilizing global event taps in combination with the bounding rects that I store anyways, but do not want to do that because it would require accessibility permissions and add a lot of overhead.

**Comment by es183923** [comment]
Okay, thanks!
