### ISSUE TITLE
Incorrect Unicode character rendering

### ISSUE THREAD

**Issue by remi-gelinas** [FelixKratz/SketchyBar#176]
I'm trying to do a simple item config using a private space unicode icon from the font I use, `PragmataPro` - which oddly enough works fine when I don't set any font on the bar/defaults/item itself, but as soon as I set the font on the item, the character is rendered as a question mark instead. Oddly enough, even when the font is set/unset, the character is only rendered correctly in the label, but not the icon.

Sample configuration (in its entirety) is as follows:

```sh
sketchybar    --bar                       color=0xFF2E3440                                          \
                                          height=26                                                 \
                                                                                                    \
              --default                   drawing=on                                                \
                                          lazy=off                                                  \
                                          updates=when_shown                                        \
                                          icon.font="PragmataPro Mono Liga:Regular:14.0"            \
                                          icon.color=0xffffffff                                     \
                                          label.color=0xffECEFF4                           \
                                          label.highlight_color=0xff8CABC8                 \

sketchybar --add         event           battery                                           \
                                                                                           \
sketchybar --add         item            battery right                                     \
           --set         battery     label=""                                             \
           --set         battery     script="~/.config/sketchybar/scripts/battery.sh"      \
           --subscribe   battery     battery                                               \

  sketchybar --update

  echo "sketchybar configuration loaded.."
```

The font is installed (and the icon renders correctly in my terminal, oddly enough though not VSCode), and I also have the default font cask installed. I've ensured that my environment `LANG` and the Homebrew `LANG` both match `en_CA.UTF_8`, to ensure I wasn't logging a duplicate of #154.

Is there something I'm missing about configuring the correct font for icons and labels or something? Is there an issue with actual font configuration string?

The font name verbatim by the way is one of three variants = `PragmataPro`, `PragmataPro Mono`, or `PragmataPro Mono Liga`, and that font name is copied from terminal configs that do render it correctly.

**Comment by remi-gelinas** [comment]
After some playing around, setting the fonts to `PragmataPro:Regular:18.0` works just fine. It only has issues as soon as I change to a variant, like `PragmataPro Mono` or `PragmataPro Mono Liga`.

**Comment by FelixKratz** [comment]
Lets go through the oddities step by step, maybe this will bring light to some of them and bring us closer to a fix for the issue you are facing:

1.
> I'm trying to do a simple item config using a private space unicode icon from the font I use, `PragmataPro` - which oddly enough works fine when I don't set any font on the bar/defaults/item itself, but as soon as I set the font on the item, the character is rendered as a question mark instead.

The default font sketchybar uses is the Hack Nerd Font, so if you don't set any font it will default to that and all nerd font icons will work. If you then set a font and the icon is not working anymore, that might hint at an issue with the font in question.

2.
> Oddly enough, even when the font is set/unset, the character is only rendered correctly in the label, but not the icon.

In the config you attached you only change the `icon.font` property, so together with 1. it makes perfect sense that it would only work for the label, because that is still using the default Hack Nerd Font.

3.
> After some playing around, setting the fonts to `PragmataPro:Regular:18.0` works just fine. It only has issues as soon as I change to a variant, like `PragmataPro Mono` or `PragmataPro Mono Liga`.

This, and 1.+ 2. leads me to believe that those variants might not be properly patched for nerd fonts. I have confirmed that variants should be working fine by testing with the Hack Nerd Font Mono variant.

Could you please try with a different font if the same issue persists and report back? E.g. with some other mono font in the nerd font family. If the issue persists, we might be facing some locale specific problems again.

**Comment by remi-gelinas** [comment]
Your variant patching point was spot on! Although the glyph existed, for some reason it was not showing - I ran all the variants through the nerdfont patcher, and it looks like it all works now. Thanks a ton!
