### ISSUE TITLE
Add option label highlight

### ISSUE THREAD

**Issue by andreicorpo** [FelixKratz/SketchyBar#18]
Hi! Could there be an option to set a `label_highlight_color` similar to how `icon_highlight_color` works?

**Comment by FelixKratz** [comment]
I think I want to make this accessible to scripting, see #32.

**Comment by FelixKratz** [comment]
You can now (since eebd5ebdd5a502b0f185ea7fcada287165a89bcb) fully configure everything about the selected space with a custom space script (see the updated README scripting section for more info). The highlighting of the label works fully analogous to that of the icon. In the plugins folder is an example script that does what you ask for, you just have to add the script to the space components.

**Comment by andreicorpo** [comment]
This idea is awesome indeed. There is a small delay between updating the icon and updating the label, but maybe it's my machine that's slow. Thank you for the awesome update!

**Comment by FelixKratz** [comment]
You can fix the delay between label and icon by freezing the bar while changing the highlights:
```bash
#!/usr/bin/env bash

if [ "$SELECTED" = "true" ]; then
  sketchybar -m freeze on
  sketchybar -m set $NAME label_highlight on
  sketchybar -m set $NAME icon_highlight on
  sketchybar -m freeze off
else
  sketchybar -m freeze on
  sketchybar -m set $NAME label_highlight off
  sketchybar -m set $NAME icon_highlight off
  sketchybar -m freeze off
fi
```
This should eliminate the offset between label and icon.

**Comment by andreicorpo** [comment]
Works perfectly now! Thank you!

**Comment by FelixKratz** [comment]
While using the script with freezing I realized that the colors are not updated properly sometimes. I will have to look into that more closely.
