### ISSUE TITLE
shadows are restricted to inside the box of the item

### ISSUE THREAD

**Issue by es183923** [FelixKratz/SketchyBar#199]
Configured with background shadow enabled, angle as 30, distance as 10, and color as all white.

Observe that the shadow does not go outside of the box of the item, even though it should. Otherwise, the shadow won't work properly.

![CleanShot 2022-06-14 at 15 56 25](https://user-images.githubusercontent.com/72744903/173677348-3b87e035-b317-4410-a15a-9d03185dcf52.png)

**Comment by FelixKratz** [comment]
The shadow is vertically limited to the height of the bar (which I believe makes sense), if you enable a background color for the bar you will see that it is cut off exactly where the bar is supposed to stop. The horizontal limit is a problem and I will fix it asap.
The same is true for the text shadows, when you create a large shadow distance like this it gets cut off to early horizontally.

**Comment by es183923** [comment]
I don't think this makes sense. Suppose you want a big shadow. Then, it would get cut off early, and won't properly display the whole shadow.

**Comment by FelixKratz** [comment]
If you look at it this way I think it makes sense:
The bar is a limited screen area where everything needs to be displayed, by allowing items to draw outside of the bar (except popups) the bar height is not tolerated correctly and the offsets for e.g. yabai will not be correct anymore. In principle I could allow for items to be placed anywhere on the screen, but I believe it is better to stay within the bounds of the bar, such that we have a clear and concise drawing area.

The solution to your problem is simple, just make the bar bigger and give it a negative y_offset, such that you have the same placement as before, but more space for the shadow.

**Comment by es183923** [comment]
Ok, that works, but is a bit less convenient. Thanks though!

**Comment by es183923** [comment]
Unfortunately, this doesn't work, as then, as graphs don't respect y_offset. I’ll make a separate issue for that.

**Comment by es183923** [comment]
Actually, this still is an issue, as the shadow is still limited horizontally and cannot escape the item box's bounds. THis makes it impossible to have a shadow that is to the bottom right of the item, for the entire item

**Comment by FelixKratz** [comment]
Can you try current master? It should at least fix the bounding box problem

**Comment by es183923** [comment]
It seems to have fixed some of them, but not all of them... 
![CleanShot 2022-06-14 at 18 05 15](https://user-images.githubusercontent.com/72744903/173697189-65cb8c3e-28e4-44bb-bdfb-5eed2d509bbc.png)
Observe how all of them have the horizontal issue fixed, except the second to last and last ones on the left side, and the middle one on the right side.

**Comment by FelixKratz** [comment]
Can you try this one f6f3e0cccc354543293ca2481a43e197821831de it should fix the remaining problems

**Comment by es183923** [comment]
Works now.
