### ISSUE TITLE
Only 1 2 3 and > showing up when following the guide

### ISSUE THREAD

**Issue by Gitmaster511** [FelixKratz/SketchyBar#214]
I followed the guide https://felixkratz.github.io/SketchyBar/setup. But only 1 2 3 < and a clear bar shows up. I tried making the plugins excellence and everything but nothing seems to work. Am I missing something? I'm currently running on a m1 mac Monterey 12.4. After remaking the file nothing is showing up.

**Comment by FelixKratz** [comment]
I think you might not have copied all revelant config files, how does your `~/.config/sketchybar` folder look like? And what are the permissions on the plugin files? Try to start `sketchybar` directly from terminal, then you will see the error messages.

**Comment by Gitmaster511** [comment]
Nothing shows up in the ~/.config/sketchybar folder. I don't see anything but a dark line which I can move up and down using the sketchybar --bar y_offset tool. I followed the guide exactly. I cloned the git repository and make it. Nothing happend but the line

**Comment by FelixKratz** [comment]
You need to copy the `sketchybarrc` and `plugins` folder from the cloned repo to `~/.config/sketchybar/` and make all the scripts executable via `chmod +x`  if you want to use the default config, otherwise you need to create a new config to configure from scratch.

If you install via brew the copying of the default config step is included in the guide. It is not included when compiling from source.
