### ISSUE TITLE
SketchyBar gets redrawn causing delay when Reduce Motion turned on

### ISSUE THREAD

**Issue by ChaosInTheCRD** [FelixKratz/SketchyBar#249]
I have "Reduced Motion" Turned on in the system preferences ( Accesibility > Display > Reduce Motion) to make the transitions easier and less distracting.

![image](https://user-images.githubusercontent.com/28873201/189117346-116f23ce-5603-443a-9d7c-56e825c7fe47.png)

This leads to me having the bar redrawn whenever I move space, which causes delay. Is there a way that this can be resolved? I guess it would require for the window to be drawn on every single space.

**Comment by FelixKratz** [comment]
Have you tried:
```bash
sketchybar --bar sticky=on
```
which makes the bar stick to every space, instead of drawing it only on the active display.

What do you mean by "causing delay"? A redraw of the bar should not cause any delay at all.

**Comment by ChaosInTheCRD** [comment]
Hey!

Thanks for this! I was aware of `sticky=on`, but  I was experiencing some weird behaviour on one of my devices with yabai when using sketchybar where it was stopping me from interacting with the window until the bar had been drawn, and that was taking about a second or so. But that device is no longer in use and I am experiencing a new perfect experience 😄 Thanks for making some great software

**Comment by sebastian-radon** [comment]
Reopening request — this issue's core symptom (bar redraw causing a visible delay when switching spaces) is still reproducible on current SketchyBar, and the original closure doesn't reflect a real fix for it.

Environment
- SketchyBar 2.24.0 (Homebrew)
- macOS Tahoe 26.5.2
- MacBook Pro (Apple Silicon, MacBookPro18,4)
- Window manager: Amethyst (no yabai)
- sticky=on (also tested sticky=off, no difference)

Behavior
Switching desktops with the "Move left/right a space" Mission Control shortcut (Ctrl+Arrow) causes a consistent ~2 second visible delay/redraw of the bar before its content reappears on the new space.

Root cause identified
"Reduce Motion" (Accessibility → Display/Motion) is enabled. Per @FelixKratz's own analysis in #493, with Reduce Motion on, macOS blends/redraws the wallpaper layer on space change in a way that forces the bar to redraw regardless of the sticky implementation, and there is no SketchyBar-side fix for that specific case — only disabling Reduce Motion avoids it. That's confirmed by another user in #597 as well ("Turned off Reduced motion settings and all works fine").

Why reopening (vs. a new issue)
This issue already describes the exact symptom precisely ("bar gets redrawn causing delay... whenever I move space"). It was closed because the original reporter's specific yabai-related device problem resolved itself, not because the underlying Reduce-Motion-caused redraw was fixed. Right now there's no issue that documents this specific, currently-still-reproducible Reduce-Motion cause as its own tracked item — it's scattered across comments in #493 and #597. Reopening this one (or at least linking it to those threads) would help anyone else searching for this exact symptom find the real explanation instead of assuming it's fixed.

Happy to test a build or provide more diagnostics if that's useful.
