### ISSUE TITLE
modifiers when clicking on a component/item

### ISSUE THREAD

**Issue by es183923** [FelixKratz/SketchyBar#25]
Being able to do `alt - click` on a component/item would be nice to have.
eg:
```sh
sketchybar -m set <item> cmd_click_script <script>
sketchybar -m set <item> ctrl_click_script <script>
sketchybar -m set <item> alt_click_script <script>
sketchybar -m set <item> shift_click_script <script>
```

**Comment by FelixKratz** [comment]
I will soon overhaul the scripting system completely then this (and much more) will be possible.
A bit of background: I plan on impelemting following syntax for the new action/event system:
```bash
sketchybar -m action <item> <action_name>,<action_modifier> <script>
sketchybar -m event <item> <event_name> <script>
```
because I want scripting to be very powerful. This way a single item can react to action (e.g. left-click, right-click, etc. with modifiers) and events individually.

**Comment by FelixKratz** [comment]
Let me know how you like it d221d0e948ac81183dd4671940b7cd5793d0f713

**Comment by es183923** [comment]
This works, but there is one major problem. It doesn't work correctly when more than one modifier is pressed.

**Comment by es183923** [comment]
One solution is to return this as json, eg:
```json
{
	"cmd": 0,
	"alt": 0,
	"ctrl": 0,
	"shift": 0
}
```

If possible, `fn` would also be nice to add.

**Comment by FelixKratz** [comment]
I want to start it slowly with only one modifier and three mouse buttons: This should already give 12 possible click events
