### ISSUE TITLE
Item clicking still janky

### ISSUE THREAD

**Issue by FelixKratz** [FelixKratz/SketchyBar#3]
There is still a bit of jank going on with the item clicking, e.g. it only works on the primary screen as the mouse coordinates are calculated in a strange way, while the origin of the bounding rects are in individual screen coordinates.
Additionally, when the og bar is shown, clicks are registered anyways leading to super janky behaviour.

**Comment by FelixKratz** [comment]
Turns out that the fixes for #9 solved this too.

**Comment by donaldguy** [comment]
Honestly the entire click handling system has no particular reason to rely on yabai's original eventtap approach 

that makes sense for yabai (but not even spacebar) cause it needs to support arbitrary click-to-move-and-resize windows (at least with the scripting-addition)

you only need to care about clicks on your drawn UX

but I understand the appeal of using what was already there

**Comment by donaldguy** [comment]
It also has the advantage of not having to worry about focus

**Comment by FelixKratz** [comment]
Ghost clicks are now fixed bc006b5d41e0c6c569a6a6a39b1c91d8983a9ad7

**Comment by FelixKratz** [comment]
While a totally different mouse interaction system would probably be more elegant I will close this for now, as it now works as expected.

**Comment by FelixKratz** [comment]
The mouse system is completely new and does not rely on event tapping anymore since 04714615712faf99d310c9acb96dd36108480692

**Comment by l00sed** [comment]
I found that I was only able to get `click_script` to run by clicking the actual text of the defined label when a transparent background was set. Perhaps this is a known/expected behavior— but it wasn't for me.

I had setup a custom space-handling script to display active current space and inactive spaces. After changing my inactive `background.color` from 0x00000000 (completely transparent) to 0x11000000 (not completely transparent), the background and padding around the label became clickable.

The expected behavior was to have the background/padding around the label remain clickable when transparent. The new configuration (setting a nearly transparent background) was an acceptable workaround though— since the background remains essentially invisible.

**Comment by mickaelperrin** [comment]
I can confirm the "issue", having transparent backgrounds prevent the clicks workings fine.

@l00sed Thanks a lot for the tip, it works good.
