### ISSUE TITLE
`popup.topmost=false` makes popups order below the bar

### ISSUE THREAD

**Issue by chrisgrieser** [FelixKratz/SketchyBar#321]
I think this is a follow-up issue to #316. After upgrading to 2.14, popups now work correctly on the mac mini, however, `popup.topmost=false` seems to break the popups, ie.e. they do not show at all. It seems this issue only occurs on the mac mini with the said one external display.

**Comment by FelixKratz** [comment]
Can you provide the minimal config where you observe this? I will try to understand why, but I guess it will again be a bit of work to pin down what exactly it is that breaks popups on your system. I am wondering if this is happening on all mac mini/pros or if it has to do with the display. The fix for the previous issue shows that the WindowServer seems to not report a proper UUID for the monitor when it is the only connected display and should be the active one. So it is either the API that is behaving strange without a builtin display or the monitor breaks the API.

**Comment by FelixKratz** [comment]
Ah ok, I see. I think the ordering of the menu bar and the popups is actually arbitrary since they share the same window level, but are not ordered relative to each other, so ordering kind of depends on execution order.  The same problem will actually also occur if both the bar and the popups are set to be topmost. I will try to include the relative ordering in the popup logic, as I think you are correct that it is never expected to have a popup below the bar, except when popups are not topmost and the bar is topmost...

**Comment by chrisgrieser** [comment]
Can confirm, the issue also occurs on my iMac at home after updating to 2.14

**Comment by FelixKratz** [comment]
Should be fixed on master, it will be included in the next release. Till then you can install from head to get the fix for your setup.

**Comment by chrisgrieser** [comment]
thank you! can confirm that it works 🥳
