### ISSUE TITLE
Bar showing ? instead of icons and values of some plugins are wrong

### ISSUE THREAD

**Issue by g1sbi** [FelixKratz/SketchyBar#346]
I installed the bar following the instructions, and Hack Nerd Font is installed correctly since I can see it in the terminal. The battery and volume plugins don't show the icon, while the CPU one has crazy values like 500% CPU usage. I'm on Monterey 13.2.1.

**Comment by FelixKratz** [comment]
The default config does not have a cpu item? It seems you have installed a different config, which might require different fonts. You will have to look in the repo where you got the config which additional setup steps are required.

**Comment by alejandro-esquivel** [comment]
> The default config does not have a cpu item? It seems you have installed a different config, which might require different fonts. You will have to look in the repo where you got the config which additional setup steps are required.

I'm having the same issue and I followed the install instructions.

**Comment by FelixKratz** [comment]
> I'm having the same issue and I followed the install instructions.

Nerd Fonts did a breaking change in version 3.0 so if you are using the default config and are updated to the newest NerdFont version you will experience a missing clock icon. This was fixed in this commit: https://github.com/FelixKratz/SketchyBar/commit/7b0f41bddf6dd3c65d3310177b0dcc47c0d4bb59 but is not contained in the latest release. I will probably release the new version with a fix soon.

Many configs floating around use the old nerd fonts and will thus display weird icons when used with the new nerdfont version, this is very unfortunate. There seem to be tools that replace all outdated nerdfont icons with their new codepoints however.
