### ISSUE TITLE
ER: Support for multiple bars

### ISSUE THREAD

**Issue by peterhajas** [FelixKratz/SketchyBar#353]
I didn't find a prior issue or documentation about this.

It'd be great if Sketchybar supported multiple named bars. For example:

* A separately configured bar for each external display, with custom items
* A custom top / bottom bar for a display (or left/right, using the undocumented other bar positions)
* Two bars stacked on top of each other

This could likely be extended to the current syntax by naming the bar (where the default is `--bar`). For example:

```
sketchybar --bar=secondary set color=...
sketchybar --bar=tertiary --add item asdf ...
```

**Comment by FelixKratz** [comment]
Ok, so I have pondered with this idea for the last half an hour and have come up with something that is actually quite usable I think. The binary name of sketchybar can now be used as an identifier for multiple bars. I.e. if you install from HEAD you can:
```bash
ln -s /opt/homebrew/bin/sketchybar /opt/homebrew/bin/bottom_bar
```
and then run `bottom_bar` in your commandline. It will launch an additional bar which is targeted with `bottom_bar --bar ...`  and has its config in `~/.config/bottom_bar/sketchybarrc`. This is only an example but since the bars are entirely independent of each other it is possible to create as many bars as you like simply by symlinking as many bar instances as you like.

**Comment by peterhajas** [comment]
Thanks, @FelixKratz. This looks like a good way to explore multiple bars.

After copying my config and renaming the names of all my existing `sketchybar` invocations, I can now have two bars. Cool!

For syntax, I wonder if leaning on the existing `--add` semantics could work. So:

```
# add a bar
sketchybar --add bar my_bar

# change properties
sketchybar --bar my_bar set color=...

# add an item
sketchybar --bar my_bar --add item asdf
```

One thing that's missing with this approach (or the symlinked copy of `sketchybar`) is assigning a bar to a particular display. Happy to file another issue if you'd rather track that separately.

**Comment by FelixKratz** [comment]
Lets track the display options separately, it shouldnt be a problem to add more powerful display selectors.
