### ISSUE TITLE
Sketchybar is hidden when application is in fullscreen

### ISSUE THREAD

**Issue by ciarafair** [FelixKratz/SketchyBar#383]
When I maximise an application to full screen it is replaced by a blank black bar, or if I unhide my normal statusbar the original statusbar will fade in.
<img width="1710" alt="Screenshot 2023-07-11 at 5 28 40 pm" src="https://github.com/FelixKratz/SketchyBar/assets/138089831/5a893934-56e7-4961-970a-6784e4c14fb8">
<img width="1710" alt="Screenshot 2023-07-11 at 5 31 48 pm" src="https://github.com/FelixKratz/SketchyBar/assets/138089831/5e463610-602b-4ecf-aa69-7259d74d19a7">

I am using this sketchybarrc:
```Bash
#!/bin/sh

bar=(
  color=0xff24273a
  height=32
  sticky=on
  padding_left=7
  padding_right=7
)

default=(
  icon.drawing=off
  label.padding_left=4
  label.padding_right=4
  label.color=0xffcad3f5
)

sketchybar \
  --bar "${bar[@]}" \
  --default "${default[@]}"

sketchybar \
  --add item space left \
  --set space script='sketchybar --set $NAME label="[$(echo "$INFO" | jq .[])]"'\
  --subscribe space space_change


sketchybar \
  --add item app_name left \
  --set app_name script='sketchybar --set $NAME label="$USER::$INFO"' \
  --subscribe app_name front_app_switched

sketchybar \
  --add item time right \
  --set time script='sketchybar --set $NAME label="$(date "+%H:%M")"' \
             update_freq=30 \
  --subscribe time system_woke

sketchybar \
  --add item ip right \
  --set ip script='sketchybar --set $NAME label="/$(ipconfig getifaddr en0)/"'\
  --subscribe ip wifi_change

sketchybar --update
```

**Comment by FelixKratz** [comment]
This is actually expected behavior, there is an extra flag I need to clear from the window tags specifically for this:
https://github.com/FelixKratz/SketchyBar/blob/61eacaeb450deec43b3cdfc510541eaea3165b5d/src/window.c#L31

What you see is the default system behavior in fullscreen applications. Drawing the bar over fullscreen windows would 
bring many problems, e.g. the black bar is only there on notched screens and not on non-notched screens, where the bar would then obstruct the UI of the fullscreen application.
