### ISSUE TITLE
Unsetting a value

### ISSUE THREAD

**Issue by andreicorpo** [FelixKratz/SketchyBar#39]
How can i remove the `background_color` for an item/component?

Setting it to transparent(`0x00000000`), makes it look weird:

![image](https://user-images.githubusercontent.com/12585256/133304940-9b869e7b-d6bc-4263-9907-aeb83f9d884d.png)

Is there a way to unset a property?

**Comment by FelixKratz** [comment]
I think this has to do with the way I draw item backgrounds. Currently I punch a transparent hole into the bar background and then draw the item background. I wanted to do it this way because of transparency color mixing of the back background and the item background, but maybe it is better to just draw the item background on top of the bar with a transparency layer...
What I could also do to fix this is to expose the *draws_background* property, then you could simple switch off background drawing for an item altogether. I will think about this and implement something along those lines later today.

**Comment by andreicorpo** [comment]
The `draws_background` idea sound perfect!

**Comment by FelixKratz** [comment]
I made some changes to the background system in 70d9b7a9833138abb694fb58ecda4fcbfd8c4e3e which makes the item backgrounds a bit more powerful.

Specifically, the newly exposed values are:
* *draws_background*
* *background_color*
* *background_color*
* *background_border_color*
* *background_corner_radius*
* *background_border_width*

Let me know if this works, will make it available in the next release.
