### ISSUE TITLE
Alignment Issue: sf symbols vs sketchybar-app-font

### ISSUE THREAD

**Issue by mrpmohiburrahman** [FelixKratz/SketchyBar#408]
### Discussed in https://github.com/FelixKratz/SketchyBar/discussions/405

<div type='discussions-op-text'>

<sup>Originally posted by **mrpmohiburrahman** October  4, 2023</sup>

![CleanShot 2023-10-04 at 19 28 24](https://github.com/FelixKratz/SketchyBar/assets/35300157/870afee3-4aaf-4884-9768-b21713268943)

On the Sketchybar, this slack icon is coming from sketchybar-app-font ( [icon_map.sh](https://github.com/mrpmohiburrahman/dotfilesOSX/blob/b7d84c25f90d4bcf7fba8c1afc874941495b5f04/sketchybar/.config/sketchybar/plugins/icon_map.sh#L192) ).

Then I put this sf symbol ( 􀟫 ) for "Activity Indicator" ( [icon_map.sh](https://github.com/mrpmohiburrahman/dotfilesOSX/blob/b7d84c25f90d4bcf7fba8c1afc874941495b5f04/sketchybar/.config/sketchybar/plugins/icon_map.sh#L6C16-L6C18) ).

Now those two icons are not aligned. I've checked with other sf symbols, and all of them are placed slightly lower.

What should I do to make those icons aligned?</div>

**Comment by FelixKratz** [comment]
From the sketchybar side there is not much you can do, this is the way those two fonts are aligned and when combining two fonts in a single text this is to be expected. If two different fonts are used in e.g. the icon and the label of an item you can shift them around with a `y_offset`, but this is not possible if the fonts are used in the same text element.

What you could do to solve your problem is that you could add an icon for Activity Monitor to the sketchybar-app-font and align it properly with the other icons.
