### ISSUE TITLE
[FR] Scrolling text animation

### ISSUE THREAD

**Issue by albert-ying** [FelixKratz/SketchyBar#429]
It would be nice to have lengthy text automatically scrolling in the bar. (like in simple-bar

Is it implementable with the current or modified animate backend?

**Comment by FelixKratz** [comment]
I have played with text scrolling a bit here: 2ba5a6c

Currently looks like this:

https://github.com/FelixKratz/SketchyBar/assets/22680421/60bb705e-adac-4101-9860-013b697eedf9

with
```bash
sketchybar --set <name> scroll_texts=<boolean>
```
being applied to texts where the `max_chars` property is used to truncate the strings.

I will play with this some more and try to readd the ellipsis char at the right hand side of the scroll.

Is this how you would have imagined the text scrolling to work?

**Comment by albert-ying** [comment]
Yes, it looks great! BTW, does this widget you used in the screenshot also works for apple music?

**Comment by albert-ying** [comment]
I just updated and tried. It seems doesn't work to me. Is this config correct?

```
sketchybar --add item test right \
  --set test scroll_texts=on \
  max_chars=5 \
  label="This is a long test text that should scroll"
```
![CleanShot 2023-10-30 at 16 20 39@2x](https://github.com/FelixKratz/SketchyBar/assets/59846322/140c19d0-17d6-48f6-bdde-e932fa69e724)

**Comment by FelixKratz** [comment]
You need to set the `max_chars` property on the label, i.e.
```bash
sketchybar --set test label.max_chars=5
```

**Comment by albert-ying** [comment]
Ah I see, working now!

**Comment by FelixKratz** [comment]
Yeah looks a bit fast, thats probably because it has the same total duration regardless of actual text length.

If you want you can play with the parameters and see if you find something that you like:

The `15` in this line makes the text scroll every 15 seconds:
https://github.com/FelixKratz/SketchyBar/blob/9d9529cb79de62ded7346abfaf2a0bcc6cf70bd2/src/bar_item.c#L110

And here the animation itself is configured (300 meaning 300/60 = 5 seconds animation duration) the second ANIMATE_FLOAT macro is the one that makes it go backwards:
https://github.com/FelixKratz/SketchyBar/blob/9d9529cb79de62ded7346abfaf2a0bcc6cf70bd2/src/text.c#L266-L284

**Comment by FelixKratz** [comment]
I have updated this to look a bit better.
