### ISSUE TITLE
Sketchybar doesn't appear on display with notch

### ISSUE THREAD

**Issue by Cliffback** [FelixKratz/SketchyBar#476]
Hi
I'm running a three monitor setup, and SketchyBar is only showing on my two external monitors, but not on the internal display on my MacBook Pro M2 Max 16" running Sonoma 14.2.1. 

If I set topmost=on, it shows on all displays, but then I won't be able to click on anything in the original menu bar, as it shows below SketchyBar. 

I don't use Yabai, but Amethyst at the moment, but it is not related to this software, as the problem persist when quitting Amethyst

Thanks

**Comment by FelixKratz** [comment]
What happens if you set `topmost=window`?

**Comment by FelixKratz** [comment]
There seems to be a window placed by some other appliation at the regular window level on your internal display because the default window level for sketchybar is `kCGBackstopMenuLevel` and the topmost window level is just above all regular user windows. Maybe a tool for cusomizing some aspect of the notch?

**Comment by Cliffback** [comment]
Yeah, you're right. I had TopNotch installed, but not activated, as well BetterDisplay, which also can hide the notch. I uninstalled TopNotch, and made sure BetterDisplay didn't do anything with the notch. Now it works fine without topmost=window
