### ISSUE TITLE
Displays have separate Spaces

### ISSUE THREAD

**Issue by FelixKratz** [FelixKratz/SketchyBar#495]
Since v2.20.0 SketchyBar will refuse to start if the system settings "Displays have separate Spaces" is turned off. The macOS default is that this option is turned on and it is required for certain things to work properly.

The setting is located in System Settings -> Desktop & Dock -> Displays have separate Spaces and should be on.

**Comment by FancyFurret** [comment]
This unfortunately makes it impossible for me to use SketchyBar. I have a bit of a unique scenario - I have an ultrawide monitor (32:9), that in order to make the full resolution and refresh rate work with my macbook - I have to run in "Picture by Picture" mode. Meaning the monitor acts as two 16:9 displays side by side to macos. Now, in order to have windows across this middle "seam" without part of the window getting cut off, I have to disable "Displays have separate Spaces". 

It would be fantastic if SketchyBar could support this configuration (even better if we could make it so the bar can span multiple displays, so I could have one long bar spanning the full width of my ultrawide monitor, broken up into two displays in macos) (this is a pain point with macos's native bar, it only shows up on one display, ie: half of my full ultrawide monitor)

**Comment by incanus** [comment]
Related to this, I'm using SketchyBar with AeroSpace WM and they recently began recommending turning this setting off. 

https://nikitabobko.github.io/AeroSpace/guide#a-note-on-displays-have-separate-spaces

I only found out when I logged out/in to toggle the setting and SketchyBar wouldn't come up, then I tried it manually and got the error message. 

Just an FYI / linking the info for context.

**Comment by diogox** [comment]
Came here to say the same thing as @incanus.

Can this restriction be removed? Will have to use something else otherwise :(

**Comment by FelixKratz** [comment]
I am all for supporting this configuration. If I remember correctly, there where some issues with this configuration, one being that this function fails:
https://github.com/FelixKratz/SketchyBar/blob/6ff8ffabef129fa823c9b38924ab39c71ea428be/src/display.c#L43-L51
More specifically `CGDisplayCreateUUIDFromDisplayID` always returns `0` with Displays have separate spaces option deactivated, breaking several functionalities such as mouse clicks and other display related things. Also the spaces component likely needs some work, because it also assumes that displays have separate spaces. Apart from that most other things are unaffected (see https://github.com/FelixKratz/SketchyBar/issues/392#issuecomment-1892768778).

That being said, I took the lazy route back then and simply assumed no one would really need that setting disabled, hence I did not feel like putting the effort required to create a workaround solution and put in the check on startup:
https://github.com/FelixKratz/SketchyBar/blob/c713afe574d1652eee7967ea490c6061ecca9f29/src/sketchybar.c#L200-L202

**Comment by diocletiann** [comment]
works again, thanks!

**Comment by FelixKratz** [comment]
This is my first shot at it: https://github.com/FelixKratz/SketchyBar/commit/fb5923291182e5070b1aef5feaed0caaa2b36074
everything seems to work at a first glance. I would appreciate help testing this commit. There is still some work required to get it ready for a release.

**Comment by PhrantiK** [comment]
Unrelated but in the neighbourhood - https://github.com/FelixKratz/SketchyBar/discussions/213#discussioncomment-10255366

**Comment by bassamsdata** [comment]
@incanus @diogox Would you mind sharing your SketchyBar configuration for Aerospace? I've been trying to set it up but haven't had any luck so far.

Thank you in advance!

**Comment by thewinger** [comment]
> This is my first shot at it: [fb59232](https://github.com/FelixKratz/SketchyBar/commit/fb5923291182e5070b1aef5feaed0caaa2b36074) everything seems to work at a first glance. I would appreciate help testing this commit. There is still some work required to get it ready for a release.

To install this commit I have to compile from source or is there a brew-ish way of installing it?

**Comment by albinabc** [comment]
Tried compiling from source on a MBP with M3 Pro, then running `./sketchybar_arm64 -c ~/.config/sketchybar/sketchybarrc` (got "could not locate config file if not specifying the config path). Just getting a blank bar on both my screens. And I have the display have separate spaces off, since I'm also running Aerospace.  Any suggestions?

**Comment by albinabc** [comment]
https://github.com/user-attachments/assets/324632f6-9fee-4cdb-9d3b-525434dfc8c9

**Comment by albinabc** [comment]
Aha! Found this: https://github.com/FelixKratz/SketchyBar/issues/608 and updated lua, and now it's working!

**Comment by aspauldingcode** [comment]
This is great, I can't wait for this to be a feature!

**Comment by zhuoqun-chen** [comment]
Any updates on this thread? Will we able to use sketchy bar with `displays have separate spaces` disabled in the next release?

**Comment by FelixKratz** [comment]
Yes, I think it should be ok to do a release with the current state of this feature if no one else has encountered issues with the current HEAD version.

**Comment by Anaritus** [comment]
For folks who are wondering how to easily install HEAD version (which includes that fix), it is very easy.
`brew install sketchybar --HEAD`

credit to https://github.com/FelixKratz/SketchyBar/issues/646#issuecomment-2460283104

**Comment by aspauldingcode** [comment]
Omg I’m so excited

**Comment by FelixKratz** [comment]
v2.22.0 now contains compatibility

**Comment by Apatros1337** [comment]
Just a little Hint: The Documentation still states that Displays-have-seperate-Spaces needs to bee turned off but you already patched that issue with v2.22.0
Thank you for your work
