### ISSUE TITLE
Inconsistent configuration naming scheme and doc not up to date

### ISSUE THREAD

**Issue by ut0mt8** [FelixKratz/SketchyBar#75]
First of all thanks for this great project. I use it and it's awesome.

Some things we can improve : 

the config coherence.
eg : when querying the status of the bar : 

```
sketchybar -m query bar
{
	"geometry": {
		"position": "top",
		"height": 26,
		"margin": 2,
		"y_offset": 2,
		"corner_radius": 0,
		"border_width": 1,
		"padding_left": 2,
		"padding_right": 2
	},
	"style": {
		"background_color": "0xff404040",
		"border_color": "0xff929292",
		"blur_radius": 0
	},
	"state": {
		"frozen": 0,
		"topmost": 0,
		"font_smoothing": 0
	},
	"items": [
		 "s1",
		 "s2",
		 "s3",
		 "s4",
		 "clock",
		 "battery"
	]
}

```
the relevant config seems to be : 
```
sketchybar -m batch --config height=26        \
                             position=top     \
                             padding_left=2   \
                             padding_right=2  \
                             margin=2

sketchybar -m batch --config y_offset=2              \
                             border_width=1          \
                             bar_color=0xff404040    \
                             border_color=0xff929292


```
you can notice that for example bar_color is configured with background_color for example, but also why y_offset and not padding_top ? 

also 

why and whare are there is two command ? : 
```
sketchybar -m batch --config height=20
sketchybar -m batch --bar height=20
```

why also -m batch seems limited to five items ?
why also I'm forced to do the some sketchybar -m batch --bar height=XX to upgrade the display to what I wanted (this seems very buggy).

**Comment by FelixKratz** [comment]
1. Yes, bar_color and background_color is a bit inconsistent
2. *y_offset* is used because the bar can also be configured to be at the bottom of the screen.
3. The domain *config* has been renamed to *bar*, but I didnt want to hard deprecate the *config* domain, so they are fully synonymous currently, but only *bar* is in the doc, because it should be used.
4. The batch command is not limited to 5 items. Can you provide an example where this would be the case? I have my entire config in a single batch command.
5. I do not understand the last sentence, can you provide an example what exactly is buggy?

**Comment by ut0mt8** [comment]
Hey thanks you it works.
