### ISSUE TITLE
Alias components dissapear

### ISSUE THREAD

**Issue by andreicorpo** [FelixKratz/SketchyBar#77]
I have the menu bar set to auto-hide, and after sketchybar starts, everything looks great. 

But after some time (or sometimes when switching spaces) the alias components disappear. If a move my mouse on the top margin of the screen - so that the menu appears, the components also reappear in the bar.

Any idea why this happens?

**Comment by andreicorpo** [comment]
I'm really sorry for this late response. This is how I have set up the aliases. All of them follow this structure:
```sh
        # still on version 1.4 of sketchybar
	sketchybar -m batch --add component alias Stats,RAM_Mini right \
	--set Stats,RAM_Mini \
	update_freq=2 \
	icon_padding_right=-5 \
	label_padding_right=-10 \
	associated_display=1 \
```
I am running on macOS 11.4 and I do not run any app like dozer and Bartender.

**Comment by FelixKratz** [comment]
Do you notice this when running on battery or plugged in? Does that make any difference? Because my device is always plugged into the wall and I never saw this happen. It could be that the original items are not rendered under certain circumstances. I am currently working on a way to get notified about a state change in the original menu bar item window, such that I dont need to poll for change, maybe this would also help in this case but I am not sure.
